-- Example seed data for Sequence Mystery System
-- Run AFTER schema.sql

USE sequence_db;

-- ── Admin user ─────────────────────────────────────────────────────────────
-- DO NOT insert the admin user via SQL — bcrypt hashes must be generated by PHP.
-- Instead, run: php migrations/create-admin.php
-- Then delete that file.

-- ── Example sequence: The Lost Archive (sequential) ────────────────────────
INSERT INTO sequences (title, slug, description, type, start_code, finale_code,
  finale_requires_code, introduction_content, finale_content, published)
VALUES (
  'The Lost Archive',
  'the-lost-archive',
  'A mystery set in an abandoned digital archive. Players must piece together what happened to Dr. Elena Vasquez.',
  'sequential',
  'ARCHIVE2024',
  'VASQUEZ',
  1,
  '<p>You have accessed a restricted terminal. The files of <strong>Dr. Elena Vasquez</strong> have been sealed following her disappearance in March 2023.</p><p>Someone left you a note: <em>"Follow the breadcrumbs. The truth is buried in the logs."</em></p><p>Find the access codes hidden in each recovered file to uncover what happened.</p>',
  '<h2>The Truth Emerges</h2><p>Dr. Vasquez didn''t disappear. She <em>escaped</em>.</p><p>The documents you''ve uncovered prove that the corporation was using the archive to hide evidence of their illegal data collection program. Elena leaked everything to the press before going into hiding.</p><p>She is safe. And thanks to you, the world now knows the truth.</p>',
  1
);

SET @seq_id = LAST_INSERT_ID();

INSERT INTO sequence_themes (sequence_id, bg_color, text_color, button_color, btn_text_color, accent_color, font_family, container_width)
VALUES (@seq_id, '#0a0e1a', '#d0d8e8', '#4f8aff', '#ffffff', '#ff6b35', "'Courier New', monospace", '820px');

-- Clue 1
INSERT INTO clues (sequence_id, title, content, access_code, hint_text, sort_order)
VALUES (
  @seq_id,
  'Terminal Log — Entry 001',
  '<p>You''ve recovered a corrupted log file. Most entries are unreadable, but one line stands out:</p><blockquote>2023-03-14 02:47:31 | ACCESS GRANTED | User: evasquez | Location: Server Room B | Note: "Moving the package tonight. Code is REDACTED."</blockquote><p>The REDACTED portion has been scrambled. But there''s something written on the sticky note attached to the monitor...</p>',
  'REDACTED',
  '<p>Look carefully at the log entry. The access code is the word that was "REDACTED" in the file.</p>',
  0
);

-- Clue 2
INSERT INTO clues (sequence_id, title, content, access_code, hint_text, sort_order)
VALUES (
  @seq_id,
  'Encrypted Email Fragment',
  '<p>An email fragment recovered from the recycle bin:</p><blockquote><strong>From:</strong> evasquez@datacore.io<br><strong>To:</strong> [REDACTED]@journalist.net<br><strong>Subject:</strong> Evidence Package<br><br>The files are in the DELTA folder. You''ll need the project codename to open the archive. We called it <strong>PHOENIX</strong> because the data rises from the ashes no matter what they do.</blockquote>',
  'PHOENIX',
  '<p>The project codename is mentioned in bold in the email fragment.</p>',
  1
);

-- Clue 3
INSERT INTO clues (sequence_id, title, content, access_code, hint_text, sort_order)
VALUES (
  @seq_id,
  'Security Badge Photo',
  '<p>A damaged security badge was found near the server room exit. The photo shows a woman — presumably Dr. Vasquez. The badge is mostly intact.</p><p>On the back, someone has scrawled a series of letters: <strong>VASQUEZ</strong></p><p>This must be the code for the final archive...</p>',
  'FINALLY',
  '<p>Check the back of the security badge. The code is written there.</p>',
  2
);

-- ── Example sequence: Open Mode demo ───────────────────────────────────────
INSERT INTO sequences (title, slug, description, type, start_code, finale_code,
  finale_requires_code, introduction_content, finale_content, published)
VALUES (
  'The Welcome Puzzle',
  'welcome-puzzle',
  'A simple open-mode demo sequence showing all clues at once.',
  'open',
  'WELCOME',
  'SOLVED',
  1,
  '<p>Welcome to your first sequence! In open mode, all clues are visible from the start. Gather the information from each clue to find the finale code.</p>',
  '<p>Congratulations! You solved the welcome puzzle. You now understand how Sequence works.</p><p>Explore the admin panel to create your own mysteries!</p>',
  1
);

SET @seq2_id = LAST_INSERT_ID();

INSERT INTO sequence_themes (sequence_id) VALUES (@seq2_id);

INSERT INTO clues (sequence_id, title, content, access_code, sort_order)
VALUES
  (@seq2_id, 'Clue A', '<p>The first letter of the answer is <strong>S</strong>.</p>', 'UNUSED_A', 0),
  (@seq2_id, 'Clue B', '<p>The second part of the code is <strong>OLVED</strong>.</p>', 'UNUSED_B', 1),
  (@seq2_id, 'Clue C', '<p>Combine them: <em>S + OLVED = ?</em></p>', 'UNUSED_C', 2);
